import type {
  Product,
  Pet,
  ServiceProvider,
  CommunityPost,
} from "./types";

// Перенесено из prototype/lucky-paul.html (константа PRODUCTS).
// TODO: заменить на fetch к реальному backend (см. database/schema.sql -> products).
export const PRODUCTS: Product[] = [
  // --- Свой бренд: ошейники (реальные фото из каталога TIZE) ---
  {
    id: "lp01",
    name: "TZ-1017 Принт-нейлоновый ошейник",
    brand: "Lucky Paul",
    brandKind: "own",
    maker: "Произведено TIZE (Шэньчжэнь)",
    category: "collar",
    price: 45,
    spec: "S/M/L · 8 цветов · светоотражающая прострочка",
    tag: "hit",
    features: [
      "Прочная нейлоновая лента",
      "Светоотражающая прострочка для вечерних прогулок",
      "Быстросъёмная пластиковая пряжка",
      "Кастомный логотип по запросу (OEM/ODM TIZE)",
    ],
  },
  {
    id: "lp02",
    name: "TZ-1000 Ошейник со светоотражающей лентой",
    brand: "Lucky Paul",
    brandKind: "own",
    maker: "Произведено TIZE (Шэньчжэнь)",
    category: "collar",
    price: 39,
    spec: "XS–XL · 5 цветов · мягкая неопреновая подкладка",
    features: [
      "Регулируемый размер XS–XL",
      "Неопреновая подкладка для комфорта",
      "Прочная металлическая D-кольцо для поводка",
      "Доступен в 5 базовых цветах, кастомные — по запросу",
    ],
  },
  {
    id: "lp03",
    name: "TZ-TC213 LED-ошейник",
    brand: "Lucky Paul",
    brandKind: "own",
    maker: "Произведено TIZE (Шэньчжэнь)",
    category: "collar",
    price: 79,
    spec: "7 цветов подсветки · 100% влагозащита · до 12ч работы",
    tag: "new",
    features: [
      "100% водонепроницаемый корпус",
      "3 режима подсветки: постоянный, медленная и быстрая вспышка",
      "До 12 часов работы от аккумулятора 110мАч",
      "Повышает безопасность на вечерних прогулках",
    ],
  },
  // --- Свой бренд: поводки ---
  {
    id: "lp04",
    name: "TZ-2022 Прочный поводок из каната",
    brand: "Lucky Paul",
    brandKind: "own",
    maker: "Произведено TIZE (Шэньчжэнь)",
    category: "leash",
    price: 42,
    spec: "120/150см · мягкая ручка · светоотражающая прошивка",
    tag: "hit",
    features: [
      "Плотное канатное плетение",
      "Мягкая ручка с амортизацией",
      "360° вертлюжный карабин против перекручивания",
      "6 цветов в наличии, кастомные — по запросу",
    ],
  },
  {
    id: "lp05",
    name: "TZ-WL1007 Поводок для двух собак с амортизацией",
    brand: "Lucky Paul",
    brandKind: "own",
    maker: "Произведено TIZE (Шэньчжэнь)",
    category: "leash",
    price: 89,
    spec: "Растягивается до 20″ · для 2 собак одновременно",
    features: [
      "Позволяет гулять сразу с двумя собаками",
      "Амортизирующая вставка снижает рывки",
      "360° вертлюжный карабин",
      "4 цвета в наличии",
    ],
  },
  {
    id: "lp06",
    name: "TZ-MS7112 Рулетка автоматическая",
    brand: "Lucky Paul",
    brandKind: "own",
    maker: "Произведено TIZE (Шэньчжэнь)",
    category: "leash",
    price: 55,
    spec: "До 5м · система блокировки одной кнопкой",
    features: [
      "Лента до 5 метров",
      "Блокировка одним нажатием",
      "Эргономичная прорезиненная рукоятка",
      "Нагрузка до 20кг",
    ],
  },
  // --- Свой бренд: GPS (концепт, в разработке) ---
  {
    id: "lp07",
    name: "Lucky Paul GPS Collar Pro",
    brand: "Lucky Paul",
    brandKind: "own",
    maker: "Собственная разработка · интеграция с профилем питомца",
    category: "gps",
    price: 249,
    spec: "GPS-трекер в ошейнике · водонепроницаемый",
    tag: "soon",
    soon: true,
    features: [
      "Отслеживание местоположения в реальном времени",
      "Данные синхронизируются с профилем питомца в приложении",
      "Плановый запуск — после MVP маркетплейса",
      "Водонепроницаемый корпус",
    ],
  },
  {
    id: "lp08",
    name: "Lucky Paul GPS Tag Mini",
    brand: "Lucky Paul",
    brandKind: "own",
    maker: "Собственная разработка · интеграция с профилем питомца",
    category: "gps",
    price: 149,
    spec: "Компактный GPS-брелок на любой ошейник",
    tag: "soon",
    soon: true,
    features: [
      "Крепится на любой существующий ошейник",
      "Компактный лёгкий корпус",
      "Плановый запуск — после MVP маркетплейса",
    ],
  },
  // --- Партнёрские бренды ---
  {
    id: "pt01",
    name: "Classic Leather Collar",
    brand: "PetSafe",
    brandKind: "partner",
    maker: "Партнёрский бренд",
    category: "collar",
    price: 120,
    spec: "Натуральная кожа · ручная прошивка",
    features: ["Натуральная кожа", "Ручная прошивка", "Классический дизайн"],
  },
  {
    id: "pt02",
    name: "Front Range Collar",
    brand: "Ruffwear",
    brandKind: "partner",
    maker: "Партнёрский бренд",
    category: "collar",
    price: 145,
    spec: "Быстросъёмная пряжка · для активных прогулок",
    features: ["Быстросъёмная пряжка", "Усиленные швы", "Для активного отдыха"],
  },
  {
    id: "pt03",
    name: "Comfort Collar",
    brand: "Kongo",
    brandKind: "partner",
    maker: "Партнёрский бренд",
    category: "collar",
    price: 55,
    spec: "Базовая модель · мягкая подкладка",
    features: ["Мягкая подкладка", "Доступная цена", "Несколько расцветок"],
  },
  {
    id: "pt04",
    name: "Easy Walk Leash 5м",
    brand: "PetSafe",
    brandKind: "partner",
    maker: "Партнёрский бренд",
    category: "leash",
    price: 95,
    spec: "Рулетка с фиксацией ленты",
    features: ["Автоматическая рулетка", "Фиксация ленты", "5 метров"],
  },
  {
    id: "pt05",
    name: "Knot-a-Leash",
    brand: "Ruffwear",
    brandKind: "partner",
    maker: "Партнёрский бренд",
    category: "leash",
    price: 130,
    spec: "Треккинговый альпинистский канат",
    features: ["Альпинистский канат", "Для треккинга", "Высокая прочность"],
  },
  {
    id: "pt06",
    name: "Hands-Free Leash",
    brand: "Kongo",
    brandKind: "partner",
    maker: "Партнёрский бренд",
    category: "leash",
    price: 99,
    spec: "Пояс для бега с питомцем",
    features: ["Хендсфри-пояс", "Для бега и джоггинга", "Амортизация рывков"],
  },
  {
    id: "pt07",
    name: "GO Explore",
    brand: "Whistle",
    brandKind: "partner",
    maker: "Партнёрский бренд",
    category: "gps",
    price: 399,
    spec: "GPS + мониторинг активности и здоровья",
    tag: "hit",
    features: ["GPS-трекинг", "Мониторинг активности", "Мониторинг здоровья"],
  },
  {
    id: "pt08",
    name: "Fi Series 3 Collar",
    brand: "Fi",
    brandKind: "partner",
    maker: "Партнёрский бренд",
    category: "gps",
    price: 449,
    spec: "GPS-ошейник с трекингом активности",
    features: ["GPS-трекинг", "Долгий срок автономной работы", "Прочный корпус"],
  },
  {
    id: "pt09",
    name: "GPS DOG 5",
    brand: "Tractive",
    brandKind: "partner",
    maker: "Партнёрский бренд",
    category: "gps",
    price: 329,
    spec: "GPS-трекер, безлимитная геолокация",
    features: ["Безлимитная геолокация", "Лёгкий корпус", "Приложение для отслеживания"],
  },
  {
    id: "pt10",
    name: "GPS Activity Monitor",
    brand: "PitPat",
    brandKind: "partner",
    maker: "Партнёрский бренд",
    category: "gps",
    price: 279,
    spec: "Трекер активности с GPS-модулем",
    features: ["Трекинг активности", "GPS-модуль", "Крепится на ошейник"],
  },
  {
    id: "pt11",
    name: "Maxi Adult 15кг",
    brand: "Royal Canin",
    brandKind: "partner",
    maker: "Партнёрский бренд",
    category: "food",
    price: 285,
    spec: "Для крупных пород · полнорационный корм",
    features: ["Для крупных пород", "Полнорационный корм", "15 кг"],
  },
  {
    id: "pt12",
    name: "Pro Plan Adult 14кг",
    brand: "Purina",
    brandKind: "partner",
    maker: "Партнёрский бренд",
    category: "food",
    price: 245,
    spec: "С высоким содержанием белка",
    features: ["Высокое содержание белка", "Для взрослых собак", "14 кг"],
  },
  {
    id: "pt13",
    name: "Wild Prairie 11.4кг",
    brand: "Acana",
    brandKind: "partner",
    maker: "Партнёрский бренд",
    category: "food",
    price: 320,
    spec: "Беззерновой, региональные ингредиенты",
    tag: "new",
    features: ["Беззерновой состав", "Региональные ингредиенты", "11.4 кг"],
  },
  {
    id: "pt14",
    name: "Original 11.4кг",
    brand: "Orijen",
    brandKind: "partner",
    maker: "Партнёрский бренд",
    category: "food",
    price: 385,
    spec: "Биологически соответствующий рацион",
    features: ["Биологически соответствующий рацион", "Высокая доля мяса", "11.4 кг"],
  },
  {
    id: "pt15",
    name: "Science Diet Adult 12кг",
    brand: "Hill's",
    brandKind: "partner",
    maker: "Партнёрский бренд",
    category: "food",
    price: 265,
    spec: "Ветеринарная формула питания",
    features: ["Ветеринарная формула", "Сбалансированный состав", "12 кг"],
  },
  {
    id: "pt16",
    name: "Grain-Free 12кг",
    brand: "Brit Care",
    brandKind: "partner",
    maker: "Партнёрский бренд",
    category: "food",
    price: 210,
    spec: "Без зерна · гипоаллергенный состав",
    features: ["Без зерна", "Гипоаллергенный состав", "12 кг"],
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  collar: "Ошейники",
  leash: "Поводки",
  gps: "GPS-устройства",
  food: "Корм",
};
export const CATEGORY_ORDER = ["collar", "leash", "gps", "food"] as const;

// Перенесено из prototype/lucky-paul.html (константа PETS).
export const PETS: Pet[] = [
  {
    id: "rex",
    name: "Rex",
    species: "dog",
    avatar: "🐕",
    breed: "Golden Retriever",
    age: "3 года",
    weight: "28 кг",
    owner: "Алексей",
    status: "ok",
    statusLabel: "Статус: здоров",
    healthPct: 100,
    orders: [
      { date: "20.08.2026", desc: "TZ-1017 Принт-нейлоновый ошейник × 1", total: 45, status: "delivered" },
      { date: "02.08.2026", desc: "TZ-2022 Поводок × 1, Royal Canin Maxi 15кг × 1", total: 327, status: "delivered" },
      { date: "15.07.2026", desc: "Услуга: груминг (Kate Morrison)", total: 120, status: "done" },
      { date: "01.07.2026", desc: "Purina Pro Plan Adult 14кг × 2", total: 490, status: "delivered" },
      { date: "18.06.2026", desc: "Услуга: осмотр у ветеринара", total: 150, status: "done" },
      { date: "30.05.2026", desc: "TZ-TC213 LED-ошейник × 1", total: 79, status: "delivered" },
    ],
    ordersTotal: 12,
    bookings: [
      { date: "28.08.2026", desc: "Груминг — Kate Morrison", time: "14:00" },
      { date: "05.09.2026", desc: "Плановый осмотр у ветеринара", time: "10:30" },
      { date: "12.09.2026", desc: "Групповая тренировка послушания", time: "17:00" },
    ],
    stats: [
      { label: "Вес", val: "28 кг", sub: "Норма для породы", icon: "weight" },
      { label: "Активность", val: "12 500", sub: "шагов / день", icon: "activity" },
      { label: "Последний осмотр", val: "15 июл.", sub: "Плановый, без замечаний", icon: "calendar" },
      { label: "Следующая вакцина", val: "05 авг.", sub: "Просрочена — требует внимания", icon: "pet", danger: true },
    ],
    vaccines: [
      { name: "Бешенство (Rabies)", given: "10.03.2026", next: "10.03.2027", status: "ok" },
      { name: "Комплексная (DHPPi)", given: "22.01.2026", next: "22.01.2027", status: "ok" },
      { name: "Лептоспироз", given: "22.01.2026", next: "22.01.2027", status: "ok" },
      { name: "Бордетеллёз (питомник)", given: "05.08.2025", next: "05.08.2026", status: "danger" },
    ],
    docs: [
      { name: "Паспорт питомца", meta: "PDF · добавлен 12.01.2026" },
      { name: "Международный ветеринарный сертификат", meta: "PDF · добавлен 20.03.2026" },
      { name: "Родословная", meta: "PDF · добавлен 01.02.2026" },
      { name: "Страховой полис", meta: "PDF · добавлен 15.06.2026" },
    ],
  },
  {
    id: "luna",
    name: "Luna",
    species: "cat",
    avatar: "🐈",
    breed: "Британская короткошёрстная",
    age: "2 года",
    weight: "4.5 кг",
    owner: "Алексей",
    status: "ok",
    statusLabel: "Статус: здорова",
    healthPct: 100,
    orders: [
      { date: "10.08.2026", desc: "Acana Wild Prairie 11.4кг × 1", total: 320, status: "delivered" },
      { date: "22.06.2026", desc: "Услуга: груминг британца", total: 110, status: "done" },
      { date: "14.05.2026", desc: "Royal Canin (кошачий) × 1", total: 210, status: "delivered" },
    ],
    ordersTotal: 5,
    bookings: [{ date: "10.09.2026", desc: "Плановый осмотр у ветеринара", time: "11:00" }],
    stats: [
      { label: "Вес", val: "4.5 кг", sub: "Норма для породы", icon: "weight" },
      { label: "Активность", val: "Умеренная", sub: "по данным владельца", icon: "activity" },
      { label: "Последний осмотр", val: "02 июн.", sub: "Плановый, без замечаний", icon: "calendar" },
      { label: "Следующая вакцина", val: "14 фев. 2027", sub: "Актуально", icon: "pet", danger: false },
    ],
    vaccines: [
      { name: "Панлейкопения", given: "14.02.2026", next: "14.02.2027", status: "ok" },
      { name: "Ринотрахеит / Калицивироз", given: "14.02.2026", next: "14.02.2027", status: "ok" },
      { name: "Бешенство (Rabies)", given: "20.02.2026", next: "20.02.2027", status: "ok" },
    ],
    docs: [
      { name: "Ветеринарный паспорт", meta: "PDF · добавлен 18.02.2026" },
      { name: "Сертификат вакцинации", meta: "PDF · добавлен 18.02.2026" },
      { name: "Справка о стерилизации", meta: "PDF · добавлен 03.03.2026" },
    ],
  },
];

export const SERVICE_LABELS: Record<string, string> = {
  vet: "Ветеринария",
  groom: "Груминг",
  train: "Тренировки",
  board: "Передержка",
  walk: "Выгул",
};
export const SERVICE_ORDER = ["vet", "groom", "train", "board", "walk"] as const;

export const SERVICES: ServiceProvider[] = [
  { id: "s1", category: "vet", name: "Dr. Ahmed Al-Farsi", role: "Ветеринар · Dubai Pet Care Clinic", rating: 4.9, price: 150, unit: "приём", initials: "AA" },
  { id: "s2", category: "vet", name: "Dr. Sarah Mitchell", role: "Мобильный ветеринар · выезд на дом", rating: 4.8, price: 200, unit: "выезд", initials: "SM" },
  { id: "s3", category: "groom", name: "Kate Morrison", role: "Груминг-салон Paws & Style", rating: 4.9, price: 120, unit: "сеанс", initials: "KM" },
  { id: "s4", category: "groom", name: "Fatima Hussain", role: "Мобильный грумер · выезд на дом", rating: 4.7, price: 140, unit: "сеанс", initials: "FH" },
  { id: "s5", category: "train", name: "James O'Connor", role: "Кинолог · послушание и коррекция поведения", rating: 4.8, price: 180, unit: "занятие", initials: "JO" },
  { id: "s6", category: "train", name: "Lina Petrova", role: "Групповые тренировки щенков", rating: 4.6, price: 90, unit: "занятие", initials: "LP" },
  { id: "s7", category: "board", name: "Pet Hotel Marina", role: "Передержка с видеонаблюдением", rating: 4.7, price: 110, unit: "сутки", initials: "PM" },
  { id: "s8", category: "board", name: "Omar's Pet Boarding", role: "Домашняя передержка", rating: 4.9, price: 95, unit: "сутки", initials: "OB" },
  { id: "s9", category: "walk", name: "Dog Walkers UAE", role: "Ежедневный выгул", rating: 4.8, price: 60, unit: "выгул", initials: "DW" },
  { id: "s10", category: "walk", name: "Maria Walks", role: "Индивидуальный выгул с фотоотчётом", rating: 4.9, price: 70, unit: "выгул", initials: "MW" },
];

export const COMMUNITY_TAGS = [
  "Golden Retriever",
  "Британская короткошёрстная",
  "Здоровье",
  "Дрессировка",
  "Питание",
  "Общие темы",
];

export const COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: "c1", author: "Anna K.", initials: "AK", time: "2 дня назад",
    title: "Голден-ретриверы и жара в ОАЭ: как гулять летом",
    excerpt: "Гуляем только рано утром и после заката, вода всегда с собой. Как справляетесь вы?",
    tags: ["Golden Retriever", "Здоровье"], likes: 24,
    comments: [
      { author: "Dmitry V.", text: "Мы вообще перешли на охлаждающий жилет — сильно помогает даже днём." },
      { author: "Sarah", text: "LED-ошейник Lucky Paul отлично видно в темноте на вечерних прогулках." },
    ],
  },
  {
    id: "c2", author: "Fatima R.", initials: "FR", time: "3 дня назад",
    title: "Британцы и корм: что реально заходит",
    excerpt: "Перепробовали пять брендов — поделюсь, что подошло именно нашей британке.",
    tags: ["Британская короткошёрстная", "Питание"], likes: 31,
    comments: [{ author: "Omar", text: "У нас Acana зашёл лучше всего, шерсть стала заметно лучше." }],
  },
  {
    id: "c3", author: "Dmitry V.", initials: "DV", time: "4 дня назад",
    title: "Первая тренировка послушания — с чего начать?",
    excerpt: "Щенку 4 месяца, хотим начать заниматься дома перед тем как идти к кинологу.",
    tags: ["Дрессировка"], likes: 18,
    comments: [{ author: "Lina P.", text: "Начните с базовых команд «сидеть» и «ко мне» — 5-10 минут в день достаточно." }],
  },
  {
    id: "c4", author: "Sarah M.", initials: "SM", time: "5 дней назад",
    title: "LED-ошейник — спасение на вечерних прогулках",
    excerpt: "После случая на неосвещённой улице купили светящийся ошейник — теперь спокойны.",
    tags: ["Golden Retriever", "Общие темы"], likes: 40,
    comments: [{ author: "Anna K.", text: "Тоже присматриваюсь к LED-модели TZ-TC213 из каталога Lucky Paul." }],
  },
  {
    id: "c5", author: "Layla H.", initials: "LH", time: "6 дней назад",
    title: "Как понять, что кошке нужен ветеринар",
    excerpt: "Собрала признаки, на которые стоит обратить внимание — от аппетита до поведения.",
    tags: ["Здоровье"], likes: 22, comments: [],
  },
  {
    id: "c6", author: "Omar B.", initials: "OB", time: "неделю назад",
    title: "Груминг британца дома — стоит ли делать самому",
    excerpt: "Разбираемся, что можно делать самостоятельно, а с чем лучше идти к грумеру.",
    tags: ["Британская короткошёрстная"], likes: 15, comments: [],
  },
  {
    id: "c7", author: "Kate M.", initials: "KM", time: "неделю назад",
    title: "Ретривер тянет поводок — как отучить",
    excerpt: "Несколько рабочих упражнений, которые реально помогли за пару недель.",
    tags: ["Golden Retriever", "Дрессировка"], likes: 27, comments: [],
  },
  {
    id: "c8", author: "Lucky Paul Community", initials: "LP", time: "2 недели назад",
    title: "Лучшие места для выгула в Дубае",
    excerpt: "Собрали подборку парков и пляжей, где можно спускать собаку с поводка.",
    tags: ["Общие темы"], likes: 33, comments: [],
  },
];
